### ISSUE TITLE
Compilation error at Elixir 1.8.1

### ISSUE THREAD

**Issue by akhilpai** [SoftwareMansion/elixir-xattr#2]
Hello, I see a compilation error at Elixir 1.8.1. @on_load functions [should](https://hexdocs.pm/elixir/Module.html#module-on_load) be public.

** (CompileError) lib/nif.ex:1: expected @on_load function init/0 to be defined as "def", got "defp"
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:208: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6

If there are no problems, https://github.com/SoftwareMansion/elixir-xattr/pull/1 makes it so. Thank you for the library!

**Comment by mkaput** [comment]
Great! Thanks for contribution :) I'll publish a new version in few days

**Comment by mkaput** [comment]
@akhilpai https://hex.pm/packages/xattr/0.3.1 :)
